// <auto-generated />
using MVC_CoffeeApplication.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_CoffeeApplication.Migrations
{
    [DbContext(typeof(CoffeeContext))]
    [Migration("20251228110922_addedSize")]
    partial class addedSize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.Coffee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BeanOrigin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cofees");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.CoffeeSize", b =>
                {
                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<int>("CoffeeId")
                        .HasColumnType("int");

                    b.HasKey("SizeId", "CoffeeId");

                    b.HasIndex("CoffeeId");

                    b.ToTable("CoffeeSize");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.Coffee", b =>
                {
                    b.HasOne("MVC_CoffeeApplication.Models.Entities.Category", "Category")
                        .WithMany("Coffees")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.CoffeeSize", b =>
                {
                    b.HasOne("MVC_CoffeeApplication.Models.Entities.Coffee", "Coffee")
                        .WithMany("CoffeeSizes")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_CoffeeApplication.Models.Entities.Size", "Size")
                        .WithMany("CoffeeSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coffee");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.Category", b =>
                {
                    b.Navigation("Coffees");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.Coffee", b =>
                {
                    b.Navigation("CoffeeSizes");
                });

            modelBuilder.Entity("MVC_CoffeeApplication.Models.Entities.Size", b =>
                {
                    b.Navigation("CoffeeSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
